[tool.pytest.ini_options]
markers = [
    "random: marks tests as random (deselect with '-m \"not random\"')"
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
