# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        # Install boost library to OS
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update 
          sudo apt-get install -y libboost-all-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install boost
        fi
        python -m pip install --upgrade pip
        python -m pip install pytest pytype wheel
        
    - name: Install package
      run: |
        pip install ./
  
    - name: Check type consistency with pyright
      if: ${{ matrix.python-version != "3.10" }}
      run: |
        # Run pytype on python versions 3.7--3.9. Pytype does not yet support 3.10 (https://github.com/google/pytype/issues/1022)
        pytype rilacs
        pytype tests
  
    - name: Run unit tests with pytest
      run: |
        pytest
        
    - name: Build and upload wheels
      run: |
        pip wheel --no-deps ./
    
    - uses: actions/upload-artifact@v2
      with:
        name: built_wheels
        path: ./rilacs-*.whl
